### ISSUE TITLE
fasta tools

### ISSUE THREAD

**Issue by colindaven** [Nucleomics-VIB/bionano-tools#1]
Hi,

why are the two fasta tools described in the README not in the repository ? Are these too new, old or have they just been forgotten ?

Thanks,
Colin

**Comment by splaisan** [comment]
some tools are not in the Bionano section but in other parts of the GIT, look in NGS-tools

https://github.com/BITS-VIB/ngs-tools

Thanks for using these tools, let us know when they do weird,

Stephane

## 

email: stephane.plaisance@vib.be
BITS - VIB, Rijvisschestraat 126/3R, BE-9052 Zwijnaarde (Gent), Belgium
website: http://www.bits.vib.be/index.php
phone (new!): +32 9 248 16 02, fax: +32 9 244 66 10
