### ISSUE TITLE
xmapisec.pl does not correct number of molecules in header

### ISSUE THREAD

**Issue by ebioman** [Nucleomics-VIB/bionano-tools#3]
as described above, the number of molecules is in the header of the BNX file
and can subsequently change in the process of using that script

Tools such as `merco` from bionano to merge afterwards BNX files will complain if
the number of indicated molecules does not match the number of encountered molecules

**Comment by splaisan** [comment]
Hello @ebioman,
I am happy to see that someone uses my old code.
We do not have the Bionano anymore for several years now and I have to dig into my own code to try fix this, not sure it will be easy nor quick.
Can you not in the meantime count the lines of your output and fix the header manually in a text editor?
Best regards
Stephane

**Comment by ebioman** [comment]
Hi
This is actually easy to fix and if I count lines and divide by 4 I can via `sed` replace accordingly the field.
E.g.:
```
  
  for i in `ls *(full|part)*.bnx`
  do
    echo "INFO: analyzing file $i"
    channels=$(grep "Label Channels" $i | awk '{print $4}')
    lines=$(grep -c -v "^#" $i)
    if [[ "${lines}" == "0" ]]
    then
      echo "INFO: File $i is actually empty"
      molecules=0
    else
      molecules=$(expr $lines / 4)
    fi
    echo -e "Encountered $channels channels, $lines lines and finally $molecules molecules"
    if  [[ "${channels}" != "1" ]]
    then
      echo "ERROR: not prepared for 2 channels!"
      exit 1
    else
      echo "INFO: found accordingly 1 channel"
      sed -i "s@^# Number of Molecules:.*@# Number of Molecules: $molecules@" $i
    fi
  done
 ```
 Note: I have no data with 2 channels and guess one would have to adapt this accordingly.
 But this works, just wanted to point the issue out :)
 
 Edit: found that some might be empty and then this kind of failed

**Comment by splaisan** [comment]
thanks a lot for your fix!
